# Generated by Django 4.1.7 on 2023-03-10 18:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contractor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Поставщик продукции')),
            ],
            options={
                'verbose_name': 'Подрядчик',
                'verbose_name_plural': 'Подрядчики',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default=None, help_text='Введите имя материала для печати', max_length=100, null=True, verbose_name='Материал для печати')),
                ('price_contractor', models.FloatField(blank=True, default=None, help_text='За 1 м2', max_length=100, null=True, verbose_name='Себестоимость печати в руб.')),
                ('price', models.FloatField(help_text='За 1 м2', max_length=100, verbose_name='Стоимость печати в руб.')),
                ('resolution_print', models.IntegerField(blank=True, default=None, help_text='разрешение для печати на материале', null=True, verbose_name='DPI')),
            ],
            options={
                'verbose_name': 'Материал',
                'verbose_name_plural': 'Материалы для печати',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Organisation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_ul', models.CharField(help_text='Форма собственности и название', max_length=70, verbose_name='Имя юр. лица')),
                ('address_ur', models.TextField(blank=True, help_text='Полный почтовый адрес', null=True, verbose_name='Юр. Адрес')),
                ('address_post', models.TextField(blank=True, null=True, verbose_name='Почтовый Адрес')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Телефон')),
                ('email', models.EmailField(blank=True, max_length=20, verbose_name='Электронная почта')),
                ('inn', models.CharField(blank=True, max_length=12, verbose_name='ИНН')),
                ('kpp', models.CharField(blank=True, max_length=9, verbose_name='КПП')),
                ('okpo', models.CharField(blank=True, max_length=12, verbose_name='ОКПО')),
                ('published', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Опубликовано')),
            ],
            options={
                'verbose_name': 'Организация',
                'verbose_name_plural': 'Организации',
                'ordering': ['name_ul'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1, help_text='Введите количество', verbose_name='Количество')),
                ('width', models.FloatField(default=0, help_text='Указывается в см.', verbose_name='Ширина')),
                ('length', models.FloatField(default=0, help_text='Указывается в см.', verbose_name='Длина')),
                ('resolution', models.IntegerField(default=0, help_text='для баннера 72 dpi, для Пленки 150 dpi', verbose_name='Разрешение')),
                ('color_model', models.CharField(choices=[('RGB', 'rgb'), ('CMYK', 'cmyk'), ('GREY', 'Greyscale'), ('LAB', 'lab')], help_text='Для корректной печати модель должна быть CMYK', max_length=10, verbose_name='Цветовая модель')),
                ('size', models.FloatField(default=0, verbose_name='Размер в Мб')),
                ('images', models.FileField(upload_to='image/%d_%m_%y')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Добавлено')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Изменено')),
                ('Contractor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='files.contractor', verbose_name='Подрядчик')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='files.material', verbose_name='Материал')),
            ],
            options={
                'verbose_name': 'Файл',
                'verbose_name_plural': 'Файлы',
            },
        ),
    ]
