# Generated by Django 4.1.7 on 2023-03-10 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='images',
            field=models.FileField(upload_to='image/%d_%m_%y'),
        ),
    ]
