# Generated by Django 4.1.7 on 2023-03-10 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0002_alter_product_images'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='price_contractor',
            field=models.FloatField(blank=True, default=None, help_text='Себестоимость печати в руб.', max_length=100, null=True, verbose_name='За 1 метр квадратный'),
        ),
    ]
