# Generated by Django 4.1.7 on 2023-03-10 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0003_material_price_contractor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=100, verbose_name='Поставщик продукции')),
                ('order_sum', models.FloatField(verbose_name='Сумма заказа')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
                'ordering': ['user'],
            },
        ),
        migrations.AlterField(
            model_name='material',
            name='price',
            field=models.FloatField(help_text='За 1 м2', max_length=100, verbose_name='Стоимость печати в руб.'),
        ),
        migrations.AlterField(
            model_name='material',
            name='price_contractor',
            field=models.FloatField(blank=True, default=None, help_text='За 1 м2', max_length=100, null=True, verbose_name='Себестоимость печати в руб.'),
        ),
    ]
