# Generated by Django 4.1.7 on 2023-03-10 08:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0004_orders_alter_material_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='user',
            field=models.ForeignKey(max_length=100, on_delete=django.db.models.deletion.CASCADE, to='files.organisation', verbose_name='Организация'),
        ),
    ]
